### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by ayaanraj** [sidloki/aurelia-onsenui#4]
Hi, I'm using Aurelia-skeleton-esnext and installed aurelia-onsenui@0.2.5 as ` jspm install npm:aurelia-onsenui`, i'm getting error as shown in the below image
![screenshot from 2018-04-26 11-45-57](https://user-images.githubusercontent.com/29095142/39289486-f0a44da0-4949-11e8-8ce4-66bc118f931b.png)

**Comment by sidloki** [comment]
It's seems to be a polyfill problem. You can try to install `core-js`:
```bash
jspm install core-js
```
And  import the required polyfills before bootstrapping aurelia in your`index.html`:
```html
System.import('core-js/web/immediate').then(() => {
  System.import('aurelia-bootstrapper');
});
```

Or you can try the Aurelia CLI instead of the jspm based skeleton.

**Comment by ayaanraj** [comment]
Thanks, it worked like a champ
